# ============================================================================
include:

  # --------------------------------------------------------------------------
  - component: $CI_SERVER_FQDN/devsecops/cicd-catalog/image/pipeline@0.4
    inputs:
      target: glab
      unit_test_enabled: false
      structure_test_enabled: false
      job_name_suffix: " (glab)"
      merge_forward: false
      release: false

  # --------------------------------------------------------------------------
  - component: $CI_SERVER_FQDN/devsecops/cicd-catalog/image/pipeline@0.4
    inputs:
      target: bashunit
      unit_test_enabled: false
      structure_test_enabled: false
      job_name_suffix: " (bashunit)"
      build_needs:
        - image build (glab)
      merge_forward: false
      release: false

  # --------------------------------------------------------------------------
  - component: $CI_SERVER_FQDN/devsecops/cicd-catalog/release-me/check-release@0.2

  # --------------------------------------------------------------------------
  - local: templates/defaults.yml
  - local: .auto-merge-forward.gitlab-ci.yml
  - local: .auto-tag.gitlab-ci.yml
  - local: .bashunit.gitlab-ci.yml
  - local: .gitlab-release.gitlab-ci.yml
  - local: .semver.gitlab-ci.yml


# ============================================================================
workflow:
  name: CI/CD Tools Catalog Builder
  rules:
    - !reference [.rules//merge-request-as-primary-workflow, rules]


# ============================================================================
# Unfortunately, we can't dog-food this Job because the image hasn't been
# built yet ... so, we start from scratch for this Job, but later in the
# Pipeline we'll compare this Job to one that uses the Pipeline image...
pipeline version:
  extends: .pipeline-version
  image: $ROCKYLINUX_BASE_IMAGE
  before_script:
    - |
      # --- pipeline version (before) ----------------------------------------
      dnf install -y epel-release
      dnf makecache
      dnf --quiet install --assumeyes git
    - !reference [.pipeline-version,  before_script]


# ============================================================================
# Begin dog-fooding the image being built by this Pipeline
# ============================================================================


# ============================================================================
dogfood [bashunit test]:
  extends: .bashunit-test
  image: $CI_REGISTRY_IMAGE/bashunit:build.$CI_PIPELINE_IID
  before_script:
    - !reference [.bashunit-test, before_script]
  script:
    - !reference [.glab-login,    script]
    - !reference [.bashunit-test, script]



# ============================================================================
dogfood [pipeline version]:
  stage: test
  extends: .pipeline-version
  image: $CI_REGISTRY_IMAGE/bashunit:build.$CI_PIPELINE_IID
  before_script:
    - !reference [.pipeline-version,  before_script]
    - |
      # --- dogfood [pipeline-version] (before) ------------------------------
      mv ${PIPELINE_ARTIFACTS_DIR}/semver.env ${PIPELINE_ARTIFACTS_DIR}/semver.env.orig
  script:
    - !reference [.pipeline-version,  script]
    - |
      # --- dogfood [pipeline-version] ---------------------------------------
      diff --report-identical-files ${PIPELINE_ARTIFACTS_DIR}/semver.env  \
                                    ${PIPELINE_ARTIFACTS_DIR}/semver.env.orig


# ============================================================================
dogfood [merge forward]:
  extends: .auto-merge-forward
  image: $CI_REGISTRY_IMAGE/glab:build.$CI_PIPELINE_IID


# ============================================================================
dogfood [auto-tag]:
  extends: .auto-tag
  image: $CI_REGISTRY_IMAGE/glab:build.$CI_PIPELINE_IID


# ============================================================================
dogfood [gitlab-release]:
  extends: .gitlab-release
  image: $CI_REGISTRY_IMAGE/glab:build.$CI_PIPELINE_IID
