CI_PROJECT_DESCRIPTION: Foundational tools for CI/CD components
CI_PROJECT_ID: 104
CI_PROJECT_TITLE: CI-CD Tools
CI_REPOSITORY_URL: https://gitlab.westsidestreet.net/devsecops/cicd-catalog/foundation.git
