# ============================================================================
.merge-forward:
  stage: release
  image: $GLAB_JOB_IMAGE
  variables:
    GIT_DEPTH: 0
    GLAB_CHECK_UPDATE: false
    GLAB_SEND_TELEMETRY: false
    GLAB_SHOW_WHATS_NEW: false
  before_script:
    - !reference [default,                before_script]
    - |
      # --- merge forward (before) -------------------------------------------
      if [[ -z "${RELEASE_TRAIN}" ]]; then
        echo "❌  Can only merge forward from a release branch!"
        echo "    Expected: 'release/X.Y'"
        echo "    Actual: ${CI_COMMIT_BRANCH}"
        exit 10
      fi

      echo ${CICD_BOT_TOKEN} | glab auth login  --hostname ${CI_SERVER_HOST}  \
                                                --stdin
  script:
    - |
      # --- merge forward ----------------------------------------------------
      MERGE_TARGET_BRANCH=${CI_DEFAULT_BRANCH}
      NEXT_MINOR_RELEASE_BRANCH=release/${SEMANTIC_VERSION_MAJOR}.$((${SEMANTIC_VERSION_MINOR} + 1))

      if git ls-remote --exit-code --heads origin ${NEXT_MINOR_RELEASE_BRANCH}; then
        MERGE_TARGET_BRANCH=${NEXT_MINOR_RELEASE_BRANCH}
      fi

      # Fetch the *full* commit history for the target branch, in preparation:
      git fetch --quiet origin "+refs/heads/${MERGE_TARGET_BRANCH}:refs/remotes/origin/${MERGE_TARGET_BRANCH}"

      if git merge-base --is-ancestor HEAD origin/${MERGE_TARGET_BRANCH}; then
        echo "🟢 All commits from ${CI_COMMIT_BRANCH} already exist in ${MERGE_TARGET_BRANCH}."
        exit 0
      fi


      GLAB_LIST_CLI_ARGS=()
      GLAB_LIST_CLI_ARGS+=(--source-branch ${CI_COMMIT_BRANCH})
      GLAB_LIST_CLI_ARGS+=(--target-branch ${MERGE_TARGET_BRANCH})
      GLAB_LIST_CLI_ARGS+=(--output json)
      GLAB_LIST_CLI_ARGS+=(--jq 'first(.[])')

      EXISTING_MR_JSON=$(glab mr list "${GLAB_LIST_CLI_ARGS[@]}")

      if [[ -n "${EXISTING_MR_JSON}" ]]; then
        MR_IID=$(echo "${EXISTING_MR_JSON}" | jq '.iid')
        MR_URL=$(echo "${EXISTING_MR_JSON}" | jq '.web_url')

        echo "🟢 Found existing MR !${MR_IID}: ${CI_COMMIT_BRANCH} --> ${MERGE_TARGET_BRANCH}"
        echo "🔗 ${MR_URL}"
      else
        GLAB_CREATE_CLI_ARGS=()
        GLAB_CREATE_CLI_ARGS+=(--yes)
        GLAB_CREATE_CLI_ARGS+=(--auto-merge)
        GLAB_CREATE_CLI_ARGS+=(--title "Auto merge ${CI_COMMIT_BRANCH} --> ${MERGE_TARGET_BRANCH}")
        GLAB_CREATE_CLI_ARGS+=(--description "Created by Pipeline ${CI_PIPELINE_IID}")
        GLAB_CREATE_CLI_ARGS+=(--source-branch ${CI_COMMIT_BRANCH})
        GLAB_CREATE_CLI_ARGS+=(--target-branch ${MERGE_TARGET_BRANCH})

        glab mr create "${GLAB_CREATE_CLI_ARGS[@]}"
      fi
  allow_failure: true
  rules:
    - !reference [.rules//never-if-gitlab-ci-local, rules]
    - !reference [.rules//if-release-branch,        rules]
