# ============================================================================
include:
  - local: .scratch.gitlab-ci.yml


# ============================================================================
.release:
  stage: release
  interruptible: false
  variables:
    GLAB_CHECK_UPDATE: false
    GLAB_SEND_TELEMETRY: false
    GLAB_SHOW_WHATS_NEW: false
    RELEASE_README_FILEPATH: $RELEASE_NOTES_DIR/RELEASE.md
  before_script:
    - !reference [.scratch//rocky10-prerequisites,  before_script]
    - !reference [.scratch//install-glab,           before_script]
    - |
      # --- release (before) -------------------------------------------------
      echo ${GITLAB_CICD_BOT_TOKEN} | glab auth login --hostname ${CI_SERVER_HOST}  \
                                                      --stdin

      # ----------------------------------------------------------------------
      # Gather the Release Notes MD files, by type:
      declare -A RELEASE_NOTES_FILES

      if [[ -d ${RELEASE_NOTES_DIR} ]]; then
        for subdir in ${RELEASE_NOTES_DIR}/*/; do
          type=$(basename ${subdir})
          list=$(ls -1 ${RELEASE_NOTES_DIR}/${type}/*.md 2> /dev/null || true)

          if [[ -n "${list}" ]]; then
            # Convert the artifact type to Title Case:
            title=${type,,}
            title=${title//_/ }
            title=${title//-/ }
            title=$(echo "${title}" | sed -E 's/(.)/\L\1/g; s/\b(.)/\U\1/g')

            RELEASE_NOTES_FILES["${title}"]="${list}"

            for md in ${list}; do
              JOB_SETTINGS+=("📃 ${title};$(basename ${md})")
            done
          fi
        done
      fi
    - !reference [default,  before_script]
  script:
    - |
      # --- release ----------------------------------------------------------
      mkdir -p ${RELEASE_NOTES_DIR}
      echo "Release ${CI_COMMIT_TAG}" | tee ${RELEASE_README_FILEPATH}

      echo ""                               >> ${RELEASE_README_FILEPATH}
      echo "Created by [Pipeline ${CI_PIPELINE_IID}](${CI_PIPELINE_URL})"     >> ${RELEASE_README_FILEPATH}
      echo ""                               >> ${RELEASE_README_FILEPATH}

      # ----------------------------------------------------------------------
      # Process the release notes for each type:
      for title in "${!RELEASE_NOTES_FILES[@]}"; do
        echo "## ${title}(s)"               >> ${RELEASE_README_FILEPATH}
        echo ""                             >> ${RELEASE_README_FILEPATH}

        for md in ${RELEASE_NOTES_FILES["${title}"]}; do
          cat ${md}                         >> ${RELEASE_README_FILEPATH}
          echo ""                           >> ${RELEASE_README_FILEPATH}
          echo "📗 Processed ${title} Release Notes: $(basename ${md})"
        done
      done
  release:
    name: Release $CI_COMMIT_TAG
    tag_name: $CI_COMMIT_TAG
    description: $RELEASE_README_FILEPATH
  rules:
    - !reference [.rules//never-if-gitlab-ci-local, rules]
    - !reference [.rules//if-release-tag, rules]
