# ============================================================================
variables:
  BASHUNIT_VERSION: 0.40.0
  BASHUNIT_URL: https://github.com/TypedDevs/bashunit/releases/download/${BASHUNIT_VERSION}/bashunit
  GLAB_VERSION: 1.107.0
  GLAB_URL: https://gitlab.com/gitlab-org/cli/-/releases/v${GLAB_VERSION}/downloads/glab_${GLAB_VERSION}_linux_amd64.rpm


# ============================================================================
.scratch//rocky10-prerequisites:
  before_script:
    - |
      # --- scratch//rocky10-prerequisites -----------------------------------
      dnf install -y epel-release
      dnf makecache
      dnf --quiet install --assumeyes git ${ROCKYLINUX_PACKAGES}


# ============================================================================
.scratch//install-glab:
  before_script:
    - !reference [.scratch//rocky10-prerequisites, before_script]
    - |
      # --- scratch//install-glab --------------------------------------------
      dnf --quiet install --assumeyes ${GLAB_URL}


# ============================================================================
.scratch//install-bashunit:
  before_script:
    - |
      # --- scratch//install-bashunit ----------------------------------------
      mkdir -p ${INSTALL_DIR}/bashunit-${BASHUNIT_VERSION}
      curl  --location  \
            --fail  \
            --silent  \
            --show-error  \
            --remote-name  \
            --output-dir ${INSTALL_DIR}/bashunit-${BASHUNIT_VERSION}  \
            ${BASHUNIT_URL}
      chmod a=rx ${INSTALL_DIR}/bashunit-${BASHUNIT_VERSION}/bashunit
      ln -s ${INSTALL_DIR}/bashunit-${BASHUNIT_VERSION}/bashunit  /usr/local/bin/bashunit
