# ============================================================================
spec:
  inputs:

    strict:
      description:  If true, protected branchs and tags which don't conform to
                    the guidelines will fail the Pipeline.
      type: boolean
      default: true

    default_semver_prefix:
      description:  If a semantic version cannot be inferred from the CI/CD
                    Pipeline variables, this value will be used as the fallback
                    SemVer prefix.  Must be of the form vMAJOR.MINOR.PATCH
      type: string
      default: v0.0.0


---


# ============================================================================
include:


  # --------------------------------------------------------------------------
  - component: $CI_SERVER_FQDN/devsecops/cicd-catalog/foundation/defaults@release/0.3
  - component: $CI_SERVER_FQDN/devsecops/cicd-catalog/foundation/semver@release/0.3
    inputs:
      strict: $[[ inputs.semver_strict ]]
      default_semver_prefix: $[[ inputs.default_semver_prefix ]]
  - component: $CI_SERVER_FQDN/devsecops/cicd-catalog/foundation/release@release/0.3
  - component: $CI_SERVER_FQDN/devsecops/cicd-catalog/foundation/merge-forward@release/0.3
